org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]

neo_version = 21.1.235
neo_version_range = [21.1.235,)
loader_version_range = [4,)

jei_version = 19.36.0.360

mod_id = unusual_prehistory
mod_name = Unusual Prehistory
mod_license = https://github.com/platypushasnohat/Unusual-Prehistory-2/blob/main/LICENSE
mod_version = 2.0.0
mod_group_id = com.barl_inc.unusual_prehistory
mod_authors = Barl Inc.
mod_description = Revive creatures from the ancient past!
