modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "https://github.com/platypushasnohat/Unusual-Prehistory-2/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_id}.png"
authors = "${mod_authors}"
description = '''${mod_description}'''
enumExtensions = "META-INF/enumextensions.json"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "patchouli"
type = "required"
versionRange = "[1.21.1-93,)"
ordering = "AFTER"
side = "BOTH"