package com.barl_inc.unusual_prehistory.client.animations.entity.mob.cenozoic;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class GiantCampanileAnimations {

        public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(10.0F).looping()
                .addAnimation("eye_left", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, -6.43F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-14.49F, 0.0F, -8.19F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-12.99F, 0.0F, -9.4F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(-10.61F, 0.0F, -9.96F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, -9.85F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(-3.88F, 0.0F, -9.06F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -7.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(3.88F, 0.0F, -5.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.degreeVec(7.5F, 0.0F, -3.42F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.75F, KeyframeAnimations.degreeVec(10.61F, 0.0F, -0.87F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1667F, KeyframeAnimations.degreeVec(12.99F, 0.0F, 1.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5833F, KeyframeAnimations.degreeVec(14.49F, 0.0F, 4.23F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 6.43F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.4167F, KeyframeAnimations.degreeVec(14.49F, 0.0F, 8.19F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.8333F, KeyframeAnimations.degreeVec(12.99F, 0.0F, 9.4F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.25F, KeyframeAnimations.degreeVec(10.61F, 0.0F, 9.96F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.6667F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 9.85F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.0833F, KeyframeAnimations.degreeVec(3.88F, 0.0F, 9.06F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 7.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.9167F, KeyframeAnimations.degreeVec(-3.88F, 0.0F, 5.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 3.42F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.degreeVec(-10.61F, 0.0F, 0.87F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.1667F, KeyframeAnimations.degreeVec(-12.99F, 0.0F, -1.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5833F, KeyframeAnimations.degreeVec(-14.49F, 0.0F, -4.23F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, -6.43F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("thingy_left", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -10.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-2.5F, -1.29F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-4.33F, -2.5F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(-5.0F, -3.54F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(-4.33F, -4.33F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(-2.5F, -4.83F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, -5.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(2.5F, -4.83F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.degreeVec(4.33F, -4.33F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.75F, KeyframeAnimations.degreeVec(5.0F, -3.54F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1667F, KeyframeAnimations.degreeVec(4.33F, -2.5F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5833F, KeyframeAnimations.degreeVec(2.5F, -1.29F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 10.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.4167F, KeyframeAnimations.degreeVec(-2.5F, 1.29F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.8333F, KeyframeAnimations.degreeVec(-4.33F, 2.5F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.25F, KeyframeAnimations.degreeVec(-5.0F, 3.54F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.6667F, KeyframeAnimations.degreeVec(-4.33F, 4.33F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.0833F, KeyframeAnimations.degreeVec(-2.5F, 4.83F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.degreeVec(0.0F, 5.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.9167F, KeyframeAnimations.degreeVec(2.5F, 4.83F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.degreeVec(4.33F, 4.33F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.degreeVec(5.0F, 3.54F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.1667F, KeyframeAnimations.degreeVec(4.33F, 2.5F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5833F, KeyframeAnimations.degreeVec(2.5F, 1.29F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -10.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("shell", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-4.83F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-4.33F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(-3.54F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.75F, KeyframeAnimations.degreeVec(3.54F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1667F, KeyframeAnimations.degreeVec(4.33F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5833F, KeyframeAnimations.degreeVec(4.83F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.0F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.4167F, KeyframeAnimations.degreeVec(4.83F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.8333F, KeyframeAnimations.degreeVec(4.33F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.25F, KeyframeAnimations.degreeVec(3.54F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.6667F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.degreeVec(-3.54F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.1667F, KeyframeAnimations.degreeVec(-4.33F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5833F, KeyframeAnimations.degreeVec(-4.83F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("shell", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F, KeyframeAnimations.posVec(0.0F, 0.26F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.25F, KeyframeAnimations.posVec(0.0F, 0.71F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.posVec(0.0F, 0.87F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.0833F, KeyframeAnimations.posVec(0.0F, 0.97F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.5F, KeyframeAnimations.posVec(0.0F, 1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.9167F, KeyframeAnimations.posVec(0.0F, 0.97F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.posVec(0.0F, 0.87F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.75F, KeyframeAnimations.posVec(0.0F, 0.71F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5833F, KeyframeAnimations.posVec(0.0F, 0.26F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.25F, KeyframeAnimations.posVec(0.0F, -0.71F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.6667F, KeyframeAnimations.posVec(0.0F, -0.87F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.0833F, KeyframeAnimations.posVec(0.0F, -0.97F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.9167F, KeyframeAnimations.posVec(0.0F, -0.97F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.posVec(0.0F, -0.87F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.posVec(0.0F, -0.71F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5833F, KeyframeAnimations.posVec(0.0F, -0.26F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("eye_right", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 6.43F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F, KeyframeAnimations.degreeVec(14.49F, 0.0F, 8.19F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8333F, KeyframeAnimations.degreeVec(12.99F, 0.0F, 9.4F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(10.61F, 0.0F, 9.96F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 9.85F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(3.88F, 0.0F, 9.06F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 7.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(-3.88F, 0.0F, 5.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 3.42F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.75F, KeyframeAnimations.degreeVec(-10.61F, 0.0F, 0.87F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1667F, KeyframeAnimations.degreeVec(-12.99F, 0.0F, -1.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5833F, KeyframeAnimations.degreeVec(-14.49F, 0.0F, -4.23F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.0F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, -6.43F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.4167F, KeyframeAnimations.degreeVec(-14.49F, 0.0F, -8.19F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.8333F, KeyframeAnimations.degreeVec(-12.99F, 0.0F, -9.4F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.25F, KeyframeAnimations.degreeVec(-10.61F, 0.0F, -9.96F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.6667F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, -9.85F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.0833F, KeyframeAnimations.degreeVec(-3.88F, 0.0F, -9.06F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -7.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.9167F, KeyframeAnimations.degreeVec(3.88F, 0.0F, -5.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.degreeVec(7.5F, 0.0F, -3.42F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.degreeVec(10.61F, 0.0F, -0.87F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.1667F, KeyframeAnimations.degreeVec(12.99F, 0.0F, 1.74F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5833F, KeyframeAnimations.degreeVec(14.49F, 0.0F, 4.23F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 6.43F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("thingy_right", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 10.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-2.5F, 1.29F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-4.33F, 2.5F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(-5.0F, 3.54F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(-4.33F, 4.33F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(-2.5F, 4.83F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, 5.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(2.5F, 4.83F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.degreeVec(4.33F, 4.33F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.75F, KeyframeAnimations.degreeVec(5.0F, 3.54F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1667F, KeyframeAnimations.degreeVec(4.33F, 2.5F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5833F, KeyframeAnimations.degreeVec(2.5F, 1.29F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -10.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.4167F, KeyframeAnimations.degreeVec(-2.5F, -1.29F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.8333F, KeyframeAnimations.degreeVec(-4.33F, -2.5F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.25F, KeyframeAnimations.degreeVec(-5.0F, -3.54F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.6667F, KeyframeAnimations.degreeVec(-4.33F, -4.33F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.0833F, KeyframeAnimations.degreeVec(-2.5F, -4.83F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.degreeVec(0.0F, -5.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.9167F, KeyframeAnimations.degreeVec(2.5F, -4.83F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.degreeVec(4.33F, -4.33F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.degreeVec(5.0F, -3.54F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.1667F, KeyframeAnimations.degreeVec(4.33F, -2.5F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5833F, KeyframeAnimations.degreeVec(2.5F, -1.29F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 10.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0354F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.6667F, KeyframeAnimations.scaleVec(0.9567F, 1.0483F, 1.0606F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.9167F, KeyframeAnimations.scaleVec(0.9517F, 1.025F, 1.0676F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1667F, KeyframeAnimations.scaleVec(0.975F, 0.9871F, 1.035F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.8333F, KeyframeAnimations.scaleVec(1.025F, 0.9517F, 0.965F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5F, KeyframeAnimations.scaleVec(1.05F, 0.9646F, 0.93F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.75F, KeyframeAnimations.scaleVec(1.0354F, 1.0F, 0.9505F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.scaleVec(1.0F, 1.0354F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .build();

        public static final AnimationDefinition SLIDE = AnimationDefinition.Builder.withLength(10.6667F).looping()
                .addAnimation("eye_left", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-4.14F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8889F, KeyframeAnimations.degreeVec(4.82F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.7778F, KeyframeAnimations.degreeVec(15.18F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.0F, KeyframeAnimations.degreeVec(26.63F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.0F, KeyframeAnimations.degreeVec(30.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.6667F, KeyframeAnimations.degreeVec(28.48F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.3333F, KeyframeAnimations.degreeVec(24.14F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.0F, KeyframeAnimations.degreeVec(17.65F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.8889F, KeyframeAnimations.degreeVec(7.39F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.8889F, KeyframeAnimations.degreeVec(-3.19F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.7778F, KeyframeAnimations.degreeVec(-8.94F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.7778F, KeyframeAnimations.degreeVec(-9.32F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.5556F, KeyframeAnimations.degreeVec(-5.04F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.degreeVec(-4.14F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("thingy_left", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.2222F, KeyframeAnimations.degreeVec(-4.96F, -3.3F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.1111F, KeyframeAnimations.degreeVec(-3.04F, -4.73F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.degreeVec(3.54F, -4.62F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.2222F, KeyframeAnimations.degreeVec(4.83F, -3.04F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.1111F, KeyframeAnimations.degreeVec(1.29F, -0.65F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.4444F, KeyframeAnimations.degreeVec(-4.83F, 3.04F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.3333F, KeyframeAnimations.degreeVec(-3.54F, 4.62F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.degreeVec(1.91F, 4.9F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.3333F, KeyframeAnimations.degreeVec(5.0F, 3.54F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.2222F, KeyframeAnimations.degreeVec(2.5F, 1.29F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("shell", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8889F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.2222F, KeyframeAnimations.degreeVec(4.33F, 0.0F, 2.9F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.2222F, KeyframeAnimations.degreeVec(3.97F, 0.0F, 2.84F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.6667F, KeyframeAnimations.degreeVec(-3.54F, 0.0F, 1.15F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.5556F, KeyframeAnimations.degreeVec(-4.83F, 0.0F, -0.39F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.4444F, KeyframeAnimations.degreeVec(-1.29F, 0.0F, -1.83F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.8889F, KeyframeAnimations.degreeVec(4.96F, 0.0F, -2.99F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.7778F, KeyframeAnimations.degreeVec(3.04F, 0.0F, -2.69F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.0F, KeyframeAnimations.degreeVec(-3.54F, 0.0F, -1.15F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("shell", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.4444F, KeyframeAnimations.posVec(0.0F, 0.26F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8889F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.5556F, KeyframeAnimations.posVec(0.0F, 0.79F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.2222F, KeyframeAnimations.posVec(0.0F, 0.97F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.7778F, KeyframeAnimations.posVec(0.0F, 1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.2222F, KeyframeAnimations.posVec(0.0F, 0.95F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.5556F, KeyframeAnimations.posVec(0.0F, 0.87F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.3333F, KeyframeAnimations.posVec(0.0F, 0.56F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.0F, KeyframeAnimations.posVec(0.0F, 0.2F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.3333F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.7778F, KeyframeAnimations.posVec(0.0F, -0.26F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.2222F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.8889F, KeyframeAnimations.posVec(0.0F, -0.79F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.5556F, KeyframeAnimations.posVec(0.0F, -0.97F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.1111F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.5556F, KeyframeAnimations.posVec(0.0F, -0.95F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.8889F, KeyframeAnimations.posVec(0.0F, -0.87F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.6667F, KeyframeAnimations.posVec(0.0F, -0.56F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.3333F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.5556F, KeyframeAnimations.posVec(0.0F, -0.07F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("eye_right", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-9.7F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(0.8889F, KeyframeAnimations.degreeVec(-8.79F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.5556F, KeyframeAnimations.degreeVec(-4.75F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.2222F, KeyframeAnimations.degreeVec(1.55F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.1111F, KeyframeAnimations.degreeVec(11.74F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.1111F, KeyframeAnimations.degreeVec(22.52F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.5556F, KeyframeAnimations.degreeVec(26.13F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.7778F, KeyframeAnimations.degreeVec(29.92F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.4444F, KeyframeAnimations.degreeVec(27.74F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.1111F, KeyframeAnimations.degreeVec(22.86F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.0F, KeyframeAnimations.degreeVec(13.47F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.4444F, KeyframeAnimations.degreeVec(-2.52F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.8889F, KeyframeAnimations.degreeVec(-6.13F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.degreeVec(-9.7F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("thingy_right", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.2222F, KeyframeAnimations.degreeVec(-4.96F, 3.3F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.1111F, KeyframeAnimations.degreeVec(-3.04F, 4.73F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.degreeVec(3.54F, 4.62F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.2222F, KeyframeAnimations.degreeVec(4.83F, 3.04F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.1111F, KeyframeAnimations.degreeVec(1.29F, 0.65F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.4444F, KeyframeAnimations.degreeVec(-4.83F, -3.04F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.3333F, KeyframeAnimations.degreeVec(-3.54F, -4.62F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.3333F, KeyframeAnimations.degreeVec(1.91F, -4.9F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.3333F, KeyframeAnimations.degreeVec(5.0F, -3.54F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.2222F, KeyframeAnimations.degreeVec(2.5F, -1.29F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0354F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.2222F, KeyframeAnimations.scaleVec(1.0F, 1.0499F, 1.0659F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.3333F, KeyframeAnimations.scaleVec(1.0F, 1.0416F, 1.0981F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.2222F, KeyframeAnimations.scaleVec(1.0F, 1.0221F, 1.0947F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.6667F, KeyframeAnimations.scaleVec(1.0F, 0.9809F, 1.0383F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.4444F, KeyframeAnimations.scaleVec(1.0F, 0.9624F, 0.9935F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(6.8889F, KeyframeAnimations.scaleVec(1.0F, 0.9504F, 0.9207F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.0F, KeyframeAnimations.scaleVec(1.0F, 0.9646F, 0.9F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.7778F, KeyframeAnimations.scaleVec(1.0F, 0.9839F, 0.9103F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.5556F, KeyframeAnimations.scaleVec(1.0F, 1.0065F, 0.9391F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.scaleVec(1.0F, 1.0354F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .addAnimation("foot", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(1.2222F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0659F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(2.4444F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0991F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0924F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(4.8889F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0259F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(5.6667F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9805F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(7.1111F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9134F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.1111F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9002F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(8.8889F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9134F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(9.6667F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 0.9444F), AnimationChannel.Interpolations.CATMULLROM),
                        new Keyframe(10.6667F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
                ))
                .build();

        public static final AnimationDefinition MONOLITH = AnimationDefinition.Builder.withLength(0.25F).looping()
                .addAnimation("shell", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("shell", new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -14.0F, -3.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.SCALE,
                        new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
                ))
                .build();
}